config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :spaces 
  
  resources :spaces do
    resources :rentals
  end
  
  resources :rentals

   root 'spaces#index'

end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :space
  belongs_to :tenant, class_name: "User"
  belongs_to :landlord, class_name: "User"
end

app/models/space.rb
class Space < ActiveRecord::Base
  has_many :rentals, dependent: :destroy
  has_many :users, through: :rentals
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :spaces
  has_many :rentals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]
  before_action :check_landlord, only: [:approve]
  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
    @space = Space.find(params[:space_id])
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)
    @space = Space.find(params[:space_id])
    @rental.customer_id = current_user.id
    @rental.renter_id = @space.user_id
    @rental.space_id = @space.id
    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Your storage reservation has been confirmed!' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit( :user_id, :space_id)
    end
  
  def check_landlord
    if current_user != @rental.landlord
      redirect_to root_path, notice: 'You cannot approve this booking'
    end
  end
  
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]
   before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)
    @space.user_id = current_user.id
    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name, :address, :user_id, :price, :description)
    end
  
      def check_user
        if current_user.id != @space.user_id
          redirect_to root_url, alert: "Sorry, this Space belongs to someone else"\
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stustorage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>
  
   <nav class="indigo lighten-3" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">StockPile</a>
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li> 
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
 
  <% if @page =='index' %>
  <div class="parallax-container">
      <div class="parallax"><img src="http://www.thepromove.com/wp-content/uploads/2015/12/2269_rsz_students_moving.jpg" width="100%"></div>
    </div>
  
  <script>
    $(document).ready(function(){
      $('.parallax').parallax();
    });   
</script>
  <% end %>
  
  <script>Materialize.toast('<%= notice %>', 8000, 'rounded')</script>
<div class="container">
<%= yield %>
  </div>


  
</body>
</html>

app/views/rentals/_form.html.erb
<%= form_for([@space, @rental]) do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :price %>
  </div>


  <!-- Modal Structure -->
  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <h4 class="indigo-text text-lighten-3">Select Rental Time Range</h4>
       <input type="date" class="datepicker" placeholder="Start Date">
       <input type="date" class="datepicker" placeholder="End Date">
      <br>
      <%= f.submit "Store Your Stuff!",class:"deep-purple btn-large" %>
    </div>
  </div>

<% end %>

<script> $('#modal1').openModal();
 $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
        
</script>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<h1>Listing Rentals</h1>

<% @rentals.each do |rental| %>
    <div class="collection">
        <a href="#!" class="collection-item"><%= User.find(rental.renter_id).email %> rented <%= rental.space.name %> for <%= rental.space.price %> dollars </a>
      </div>
<% end %>

app/views/rentals/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<h1><i>Congratulations! </i><h1>
<h3>Your storage reservation has been confirmed</h3>
  <p>You can reach our the home owner at 555-555-5555</p>
  <p>Your check in date is 05/03/16<br>
    Your check out date is 7/24/16</p>

  <img src="http://simeonkakpovi.com/home/wp-content/uploads/2016/03/Screen-Shot-2016-03-26-at-11.31.16-AM.png" class="responsive-img">

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div> 
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing Space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<% @page = 'index' %>
<h2 class="indigo-text text-lighten-3">Storage Spaces in Washington D.C.</h2>

  <div class="row">
    <form >
      <div class="row">
        <div class="col m4">
          <div class="input-field col s12">
            <input id="text" type="text" class="validate" placeholder="Search by location">
          </div>
        </div>
        <div class="col m4">
       <div class="input-field col s12">
          <select multiple>
            <option value="" disabled selected>Select size</option>
            <option value="1">10 x 10</option>
            <option value="2">15 x 15</option>
            <option value="3">20 x 20</option>
          </select>
          <label>Search by size</label>
        </div>
        </div>
        <div class="col m4">
          <div class="input-field col s12">
            <input id="text" type="date" class="datepicker" placeholder="Search by Date">
          </div>
        </div>
      </div>
    </form>
  </div>
        
<div class ="row">
<% @spaces.each do |space| %>
  <div class="col m4">
  <div class="card">
      <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="http://flintstonemarble.com/wp-content/uploads/2014/11/basement-toronto-contractors-12.jpg">
      </div>
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4"><%= space.name %><i class="fa fa-ellipsis-v right"></i></span>
        <p><%= link_to "View!", space, class:"btn deep-purple" %></p>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4"><%= space.name %><i class="fa fa-times right"></i></span>
        <p>Address: <%= space.address %><br>
        Description: <%= space.description %><br>
          <% if user_signed_in? %>
            <% link_to 'Edit', edit_space_path(space) %>
            <% link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </p>
      </div>
  </div>
 </div>
<% end %>
  </div>
<% link_to 'New Space', new_space_path %>

<script>
   $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
     

    $('select').material_select();
        
</script>

app/views/spaces/new.html.erb
<h1>New Space</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
  <div class="row">
        <div class="col s12 m6 offset-m3">
          <div class="card">
            <div class="card-image">
              <img src="http://flintstonemarble.com/wp-content/uploads/2014/11/basement-toronto-contractors-12.jpg">
              <span class="card-title"><%= @space.name %></span>
            </div>
            <div class="card-content">
              <img src="http://4.bp.blogspot.com/-7j95ujkNsJA/UdkCe2a7g7I/AAAAAAAAARs/j67uCEDKIgI/s1600/4stars1.jpg" width="25%">
              <p><%= @space.description %><br></p>
              <h4>Price $<%= @space.price %></h4>
            </div>
            <div class="card-action">
              <p><%= link_to "Store your stuff here!", new_space_rental_path(@space), class:"btn deep-purple" %></p>
            </div>
          </div>
           <ul class="collection">
    <li class="collection-item avatar">
      <img src="http://www.petzoned.com/assets/default_avatar-468e8f42276a2fd234b034f28536570b.png" alt="" class="circle">
      <span class="title">Great Experience</span>
      <p>The homeowner was very friendly <br>
         I got all my stuff back on time. Would recommend!
      </p>
      <a href="#!" class="secondary-content"><i class="fa fa-star"></i></a>
    </li>
    <li class="collection-item avatar">
      <img src="http://www.petzoned.com/assets/default_avatar-468e8f42276a2fd234b034f28536570b.png" alt="" class="circle">
      <span class="title">It was Ok</span>
      <p>The homeowner wasn't there the first time <br>
         It was a lot larger thank expected through
      </p>
      <a href="#!" class="secondary-content"><i class="fa fa-star"></i></a>
    </li>
    <li class="collection-item avatar">
      <img src="http://www.petzoned.com/assets/default_avatar-468e8f42276a2fd234b034f28536570b.png" alt="" class="circle">
      <span class="title">Twas Dope</span>
      <p>This was easy and wonderful <br>
         I saved a lot of bread too
      </p>
      <a href="#!" class="secondary-content"><i class="fa fa-star"></i></a>
    </li>

  </ul>
         
          <% link_to 'Edit', edit_space_path(@space) %> 
<% link_to 'Back', spaces_path %>
        </div>
      </div>
            